### ISSUE TITLE
SSML intermittent error

### ISSUE THREAD

**Issue by mcgeo52** [eheikes/tts#65]
The code is:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import apv
import audioread
import boto3
from boto3 import client
from boto3 import Session
from botocore.exceptions import BotoCoreError, ClientError
import csv
import mysql.connector
from mysql.connector import Error
import os
import sys
import wave

access_key = apv.aws["aws_key1"]
secret_key = apv.aws["aws_key2"]

polly_client = boto3.Session(
    aws_access_key_id=access_key,
    aws_secret_access_key=secret_key,
    region_name='us-west-2').client('polly')
   
event_ID = sys.argv[1]
event = str(event_ID)

pathout = "/var/www/html/data/event"

db_host = apv.sql["host"]
db_name = apv.sql["name"]
db_user = apv.sql["user"]
db_pass = apv.sql["pass"]
db_port = apv.sql["port"]
        
db = mysql.connector.connect(
    host = db_host,
    database=db_name,
    user=db_user,
    password=db_pass,
    port=db_port)
    
sql_select_Query = "select * from Voice where event_ID = %s"
cursor = db.cursor()
cursor.execute(sql_select_Query, (event_ID,))
record = cursor.fetchall()
for row in record:
    voice = row[1]
    names = row[2]
    text1a = row[3]
    text1b = row[4]
text1 = text1a + " " + names + " " + text1b
    
#if voice == "Matthew" or voice == "Joanna":
#    spkOpen = '<speak><amazon:domain name="news">'
#    spkClose = '</amazon:domain></speak>'
#else:
spkOpen = '<speak>'
spkClose = '</speak>'
    
fileOut1 = pathout + event + '/event' + event + '-1.wav'
response1 = polly_client.synthesize_speech(VoiceId=voice,
    Engine='neural',
    OutputFormat='pcm',
    TextType='ssml',
    Text=spkOpen + text1 + spkClose)

wav_file = wave.open(fileOut1, 'wb')
wav_file.setparams((1, 2, 16000, 0, 'NONE', 'NONE'))
wav_file.writeframes(response1['AudioStream'].read())
```

This is obviously being run against a database. Some events work. Some don't.

I have set the name, text1a, and text1b values the same in two different events for test purposes. If the script works for an event in the database, it doesn't matter what I have name, text1a, and text1b set to, it works. Likewise, if the script does not work for an event, it doesn't matter what I have name, text1a, and text1b set to, it won't work.

For the case where it doesn't work, I get the following results when I run the script:

```
Traceback (most recent call last):
  File "/var/www/html/py-scripts/wed-voice1.py", line 67, in <module>
    Text=spkOpen + text1 + spkClose)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidSsmlException: An error occurred (InvalidSsmlException) when calling the SynthesizeSpeech operation: Invalid SSML request
```

Any idea what the problem might be?

**Comment by mcgeo52** [comment]
Test data:
text1a = "Can you help us,"
names = "Bob and Dotty?"
text1b = "Please respond today."

**Comment by eheikes** [comment]
Sorry, I think you're in the wrong place. This project is a Node.js (Javascript) app for AWS Polly. Since you're using boto3, you might try one of the following:

* [the AWS community forum](https://forums.aws.amazon.com/forum.jspa?forumID=132) for Python
* [the boto3 project](https://github.com/boto/boto3) issues

**Comment by mcgeo52** [comment]
Sorry. I have reposted as a(nother) boto3 project issue.
